apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1-deployment
  namespace: frontend1-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name: frontend1
        image: tayyabqaisar/frontend1:latest
        ports:
        - containerPort: 3000
