apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-deployment
  namespace: backend1-namespace
spec:
  replicas: 1   
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: tayyabqaisar/backend1:latest  
        ports:
        - containerPort: 8000
