apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2-deployment
  namespace: frontend2-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2
    spec:
      containers:
      - name: frontend2
        image: tayyabqaisar/frontend2:latest
        ports:
        - containerPort: 3000
