apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend10-deployment
  namespace: backend10-namespace 
spec:
  replicas: 10   
  selector:
    matchLabels:
      app: backend10
  template:
    metadata:
      labels:
        app: backend10
    spec:
      containers:
      - name: backend10
        image: tayyabqaisar/backend10:latest  
        ports:
        - containerPort: 8000
