apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend9-deployment
  namespace: backend9-namespace
spec:
  replicas: 9   
  selector:
    matchLabels:
      app: backend9
  template:
    metadata:
      labels:
        app: backend9
    spec:
      containers:
      - name: backend9
        image: tayyabqaisar/backend9:latest  
        ports:
        - containerPort: 8000
